language: generic
sudo: required
services:
        - docker

before_deploy:
        - docker build -t tcesario/simpleweb -f Dockerfile .

deploy:
        edge: true
        provider: elasticbeanstalk
        region: "us-east-2"
        app: "simpleweb2"
        env: "Simpleweb2-env"
        bucket_name: "elasticbeanstalk-us-east-2-870598663126"
        bucket_path: "docker"
        on:
          branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
